# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: '1.2'
_src_path: https://github.com/m-birke/python-project-template.git
package_name: tdms_cli
project_description: Small util to analyze TDMS files quickly via CLI
project_name: tdms-cli
